### ISSUE TITLE
Sync with upstream

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/statusfpo#1]
Should this repo move to https://pagure.io/fedora-status ?

https://pagure.io/fedora-infrastructure/issue/6553#comment-509776

**Comment by mizdebsk** [comment]
For me, the answer is "no". The status page should be independent of Fedora infrastructure as much as possible. For example, we want to be able to update it even if Pagure is down.

**Comment by pypingou** [comment]
They are entirely different repos

**Comment by abitrolly** [comment]
Yes, so how to sync https://github.com/fedora-infra/statusfpo/tree/master/wsgi contents with https://pagure.io/fedora-status/ and make sure that useful fixes end up in upstream?

**Comment by pypingou** [comment]
>    If it is not getting any fixes 

What makes you think it doesn't?

**Comment by pypingou** [comment]
>    Last commits almost 3 years ago
>    https://pagure.io/fedora-status/commits/master

And what makes you think it has needed any changes since?

**Comment by abitrolly** [comment]
README in this repository https://github.com/fedora-infra/statusfpo/ has broken links to upstream. Diff shows that codebase diverted, but no things are merged upstream either.

Also, `manage.py` is put out of webroot here, which is a good thing, and `generator.py` probably should follow with more clear separation of templates and static data/html. Upstream lacks this.
