### ISSUE TITLE
Make status page responsive 

### ISSUE THREAD

**Issue by 0xMRTT** [fedora-infra/statusfpo#34]
Currently, the status page isn't responsive at all. 

![IMG_20220819_130006](https://user-images.githubusercontent.com/105598867/185604747-86016ef5-443d-4c2d-8a1a-99349d24b8d7.jpg)

If you want, I can make a PR ?

**Comment by ryanlerch** [comment]
we are currently using bootstrap breakpoints that scale the page down pretty nicely on smaller screens. 

what specific responsive changes are required here?
